# Generated by Django 4.2.5 on 2023-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=123123, upload_to='recipes/media', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
